config/routes.rb
Rails.application.routes.draw do
  resources :routines
  get 'welcome/index'
  get '/about', to: "welcome#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/logbook', to: "welcome#logbook", as: "logbook"

  resources :workouts, only: [:destroy, :create, :update, :view, :edit] do
    delete '/edit/removeExercise', to: "workouts#remove_exercise", as: "remove_exercise"
    patch 'edit/addExercise', to: "workouts#add_exercise", as: "add_exercise"
  end

  resources :exercises do
    resources :exercise_sets, only: [:destroy, :create, :edit, :update]
  end

  namespace :api do
    resources :routines, only: [:index, :create, :update, :destroy]
    resources :profiles, only: [:index, :show]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users, :controllers => { registrations: 'users/registrations' }
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_and_belongs_to_many :exercises
  has_many :exercise_sets, through: :exercises, dependent: :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :exercise_sets

  validates :title, presence: true
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!, :find, only: [:destroy, :show, :edit, :update]
  def index
    @workouts = current_user.workouts
  end

  def destroy
    id = @workout.id

    # This is needed in order to circumvent errors.
    @workout.exercises.map { |e| e.exercise_sets.destroy_all }

    if @workout.destroy
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.remove("workout_#{id}")}
        format.html { redirect_to logbook_path(id: params[:user_id]) }
      end
    end
  end

  def create
    @workout = current_user.workouts.new(workout_params)
    if @workout.save then redirect_back(fallback_location: '/') end
  end

  def show
    @exercises = Exercise.where(id: @workout.exercise_ids)
  end

  def edit
    @workout.exercises.each do |ex|
      ex.exercise_sets.build
    end

    if current_user != @workout.user then not_found!("Not found") end
  end

  def update
    if @workout.update(workout_params)
      # redirect_to workouts_path
      @exercises = params[:workout][:exercise_ids].map { |ex| Exercise.find(ex)}

      # exercise added
      respond_to do |format|
        format.html { redirect_to edit_workout_path(params[:id]) }
        format.turbo_stream
      end
    end
  end

  def workout_params
    params.require(:workout).permit(:title, :duration, :description, exercise_ids: [])
  end

  def find
    if params[:id]
      @workout = Workout.find(params[:id])
    end
  end

  def not_found!(msg)
    raise ActionController::RoutingError.new(msg)
  end

  def remove_exercise
    @workout = Workout.find(params[:workout_id])
    exercise = Exercise.find(params[:exercise_id])

    exercise.exercise_sets.where(workout_id: @workout.id).destroy_all
    @workout.exercises.delete(exercise)

    if @workout.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: '/') }
        format.turbo_stream { render turbo_stream: turbo_stream.remove("edit_exercise_#{params[:exercise_id]}") }
      end
    end
  end


  def add_exercise
    @workout = Workout.find(params[:workout_id])
    @exercise = Exercise.find(params[:exercise_id])

    @workout.exercises.append(@exercise)

    if @workout.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: '/') }
        format.turbo_stream { render turbo_stream: turbo_stream.append("exercises", partial: "exercises/exercise", locals: {exercise: @exercise, is_workout: true})}
      end
    end
  end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_workout.html.erb
<%= turbo_frame_tag dom_id(workout), target: '_top' do %>
    <% if current_user.id == workout.user_id %>
        <div class="flex justify-between p-1">
            <%= link_to workout.title, edit_workout_path(workout.id), class: "text-2xl font-semibold hover:text-carnage-red-pressed transition ease-in-out" %>

            <%= button_to "Remove", workout_path(workout.id, user_id: params[:id]), method: :delete, class: "rounded-3xl font-semibold hover:bg-carnage-red-pressed transition ease-in-out py-2 px-8
            text-center text-white bg-carnage-red" %>
        </div>

    <% else %>
        <%= link_to workout.title, workout_path(workout.id), class: "text-2xl" %>
    <% end %>
    <p class="inline-flex"> (<%= workout.created_at.strftime("%d/%m/%Y") %>)</p>
    <br>
<% end %>

app/views/workouts/add_exercise.turbo_stream.erb
<%= turbo_stream.remove("edit_exercise#{@id}") %>

app/views/workouts/edit.html.erb
<%= turbo_stream_from :exercises %>
<%= form_with model: @workout do |f| %>
    <div class="mx-auto text-center flex items-center justify-center">
        <img src="/assets/icon.png" class="w-[30px] sm:w-[55px]" />
        <%= f.text_field :title, required: true, placeholder: @workout.title, class: "text-red-50 border-b-white text-2xl bg-carnage-main" %>
    </div>

    <div class="px-4">
    <%= turbo_frame_tag "exercises", class: "flex flex-wrap" do %>
        <% @workout.exercises.each do |ex| %>
            <%= render ex, is_workout: true %>
        <% end %>
    <% end %>

    <%= render DialogComponent.new(title: "Add Exercise", close_button_text: "Save Changes") do |e| %>
        <% Exercise.all.each do |ex| %>
        <div class="mb-3 bg-[#212125] rounded-lg p-2 mx-2">
            <p class="text-white font-bold"><%= ex.name %></p>
            <p class="text-white text-center"><%= ex.emphasis %></p>
            <%= button_to "Add Exercise", workout_add_exercise_path(workout_id: @workout.id, exercise_id: ex.id), method: :patch, class: "outline outline-4 outline-teal-400 text-teal-400 font-semibold hover:text-teal-300 p-2 rounded-xl text-sm mt-3" %>
        </div>
        <% end %>
    <% end %>
    <div class="w-full text-center mt-10">
        <button type="button" onclick="document.getElementById('dialog').showModal();"
        class="rounded-3xl font-semibold hover:bg-carnage-red-pressed transition ease-in-out py-2 px-8
                text-center text-white bg-carnage-red">+ Add Exercise</button>
    </div>
    </div>
<% end %>

app/views/workouts/index.html.erb
<div class="md:container px-4 mx-auto">
  <h1 class="text-6xl font-bold text-slate-100 text-center">Workouts</h1>
  
  <div class="gap-4 mx-auto flex justify-center">
    <% @workouts.each do |workout| %>
      <div class="max-w-md my-4 bg-slate-900 rounded-b-lg text-center">
        <p class="bg-red-500 rounded-t-lg font-bold text-slate-100"><%= workout.title %></p>
        <p class="m-1 text-slate-100">Bro made an empty workout :skull:</p>  

        <div class="inline-flex items-baseline">
        <%= button_to "Edit", edit_workout_path(workout), method: :get, class: "text-slate-100 px-8" %>
        <%= button_to "Delete", workout_path(workout), method: :delete, class: "text-red-500 hover:text-red-700 transition-colors duration-300  px-8" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="md:container p-16 mx-auto text-center">
    <%= link_to "+ New", new_workout_path, class: "text-slate-100 text-4xl font-bold px-4 py-2 bg-red-500 rounded-full" %>
  </div>
</div>

app/views/workouts/main.html.erb
<div class="md:container px-4 mx-auto">
  <h1 class="text-6xl font-bold text-slate-100 text-center">Workouts</h1>
  
  <div class="grid grid-flow-col gap-4 mx-auto">
    <% @workouts.each do |workout| %>
      <div class="max-w-md my-4 bg-slate-900 rounded-b-lg text-center">
        <p class="bg-red-500 rounded-t-lg font-bold text-slate-100"><%= workout.title %></p>
        <p class="m-1 text-slate-100">Bro made an empty workout :skull:</p>  

        <div class="inline-flex items-baseline">
        <%= button_to "Edit", edit_workout_path(workout), method: :get, class: "text-slate-100 px-8" %>
        <%= button_to "Delete", workout_path(workout), method: :delete, class: "text-red-500 hover:text-red-700 transition-colors duration-300  px-8" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="md:container p-16 mx-auto text-center">
    <%= link_to "+ New", new_workout_path, class: "text-slate-100 text-4xl font-bold px-4 py-2 bg-red-500 rounded-full" %>
  </div>
</div>

app/views/workouts/remove_exercise.turbo_stream.erb
<%= turbo_stream.remove "edit_exercise_#{@id}" %>

app/views/workouts/show.html.erb
<div class="md:container px-auto px-4">
  <p class="text-slate-100 text-4xl font-extrabold"><%= @workout.title %></p>
  <div class="flex justify-center gap-8 mt-3">
    <div class="bg-slate-100 p-3 text-gray-700 rounded-xl">
      <p class="font-bold text-2xl">Exercises</p> 
      <% @exercises.each do |exercise| %>
        <p class="ml-2"><%= exercise.name %> ([] sets)</p>
      <% end %>
    </div>
    <div class="bg-red-400 p-3 text-slate-100 rounded-xl">
      <p class="font-bold text-2xl">Stats</p>
      <div class="ml-2">
        <p>Exercises performed: <b><%= @exercises.count %></b></p>
        <p>Sets performed: <b>[]</b></p>
        <p>Average intensity: <b>[]</b></p> <!--Per set intensity-->
        <p>Total intensity: <b>[]</b></p> <!--Total intensity. Asked after the user finishes the workout-->
        <p>Session duration: <b><%= @workout.duration %> min</b></p>
      </div>
      <%= button_to "Delete workout", workout_path(@workout), method: :delete, class: "w-full rounded-lg text-center text-slate-100 font-bold bg-red-500 mt-6" %>
    </div>
  </div>
</div>