config/routes.rb
Rails.application.routes.draw do
  resources :routines
  get 'welcome/index'
  get '/about', to: "welcome#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/logbook', to: "welcome#logbook", as: "logbook"

  resources :workouts, only: [:destroy, :create, :update, :view, :edit] do
    delete '/edit/removeExercise', to: "workouts#remove_exercise", as: "remove_exercise"
    patch 'edit/addExercise', to: "workouts#add_exercise", as: "add_exercise"
  end

  resources :exercises do
    resources :exercise_sets, only: [:destroy, :create, :edit, :update]
  end

  namespace :api do
    resources :routines, only: [:index, :create, :update, :destroy]
    resources :profiles, only: [:index, :show]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users, :controllers => { registrations: 'users/registrations' }
end

app/models/routine.rb
class Routine < ApplicationRecord
  has_and_belongs_to_many :exercises
  has_many :exercise_sets, through: :exercises
  belongs_to :user

  accepts_nested_attributes_for :exercise_sets
end

app/controllers/api/routines_controller.rb
class Api::RoutinesController < ApplicationController
  before_action :authenticate_devise_api_token!

  def index
    routines = current_devise_api_user.routines
    render json: routines
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /routines or /routines.json
  def index
    @routines = current_user.routines
  end

  # GET /routines/1 or /routines/1.json
  def show
  end

  # GET /routines/new
  def new
    @routine = current_user.routines.new
  end

  # GET /routines/1/edit
  def edit
    @exercise_sets = @routine.exercise_sets
  end

  # POST /routines or /routines.json
  def create
    @routine = current_user.routines.new(routine_params)

    respond_to do |format|
      if @routine.save
        format.html { redirect_to routine_url(@routine), notice: "Routine was successfully created." }
        format.json { render :show, status: :created, location: @routine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routines/1 or /routines/1.json
  def update
    respond_to do |format|
      if @routine.update(routine_params)
        format.html { redirect_to routine_url(@routine), notice: "Routine was successfully updated." }
        format.json { render :show, status: :ok, location: @routine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @routine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routines/1 or /routines/1.json
  def destroy
    @routine.destroy!

    respond_to do |format|
      format.html { redirect_to routines_url, notice: "Routine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_routine
      @routine = Routine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def routine_params
      params.require(:routine).permit(:name, :description, :user_id, exercise_sets_ids: [])
    end
end

app/helpers/api/routines_helper.rb
module Api::RoutinesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/_form.html.erb
<%= form_with(model: routine, class: "contents relative") do |form| %>
    <div class="flex gap-8 align-items-left py-16">
        <%= render SidebarComponent.new do %>
            <p class="font-semibold text-2xl text-white">Exercises</p>
            <% for ex in Exercise.all %>
                <%= render ex, is_workout: false %>
            <% end %>
        <% end %>

        <div class="w-full">
        <% if routine.errors.any? %>
            <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
            <h2><%= pluralize(routine.errors.count, "error") %> prohibited this routine from being saved:</h2>
            <ul>
                <% routine.errors.each do |error| %>
                <li><%= error.full_message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <div class="grid w-full">
                <%= form.text_field :name, placeholder: "Routine title...", class: "border-none bg-carnage-secondary rounded-lg text-white text-4xl mb-4" %>
                <%= form.text_field :description, placeholder: "Workout description...", class: "border-none bg-carnage-secondary rounded-lg text-white mb-4" %>
        </div>

        <div class="bg-carnage-secondary p-4">
            <% for set in @exercise_sets %>
            <% end %>
        </div>

        <div class="flex justify-center gap-4">
            <%= form.submit "Save Changes", class: "w-auto rounded-3xl py-2 px-8 bg-carnage-red text-white font-medium cursor-pointer" %>
        </div>

        </div>
    </div>
<% end %>

app/views/routines/_routine.html.erb
<div id="<%= dom_id routine %>">
    <div class="flex justify-between gap-4">
      <p class="text-white font-bold text-lg"><%= routine.name %></p>
        <div class="flex gap-1">
          <%= link_to "edit", edit_routine_path(routine), class: "text-white material-symbols-outlined hover:text-carnage-red" %>
          <%= button_to "delete", routine_path(routine), method: :delete, class: "text-white material-symbols-outlined hover:text-carnage-red" %>
        </div>
      </div>
      <hr>

      <p class="ml-2 mt-1 text-white"><%= routine.description %></p>
</div>

app/views/routines/edit.html.erb
<div class="pr-16">
  <%= render "form", routine: @routine %>

</div>

app/views/routines/index.html.erb
<div class="md:container">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mx-auto text-center flex items-center justify-center p-16">
    <img src="/assets/icon.png" class="w-[30px] sm:w-[80px]"></img>
    <p class="text-white ml-4 font-bold font-montserrat uppercase text-3xl sm:text-7xl">Routines</p>
  </div>


  <div class="text-center p-4">
      <%= link_to "New routine", new_routine_path, class: "rounded-3xl hover:bg-carnage-red-pressed transition ease-in-out py-2 px-8 text-white bg-carnage-red text-lg" %>
  </div>

  <div class="mx-2 text-white bg-carnage-secondary p-6 font-montserrat mt-2 rounded-3xl">
      <%= render partial: 'routines/routine', collection: @routines %>
  </div>

  <div id="routines" class="min-w-full">
  </div>
</div>

app/views/routines/new.html.erb
<div class="mx-auto md:container">
    <div class="mx-auto text-center flex items-center justify-center mt-5 sm:mt-20">
      <img src="/assets/icon.png" class="w-[30px] sm:w-[80px]"></img>
      <p class="text-white ml-4 font-bold font-montserrat uppercase text-3xl sm:text-7xl">New Routine</p>
    </div>
  <%= render "form", routine: @routine %>
</div>

app/views/routines/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @routine %>

  </div>
</div>