config/routes.rb
Rails.application.routes.draw do
  resources :routines
  get 'welcome/index'
  get '/about', to: "welcome#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/logbook', to: "welcome#logbook", as: "logbook"

  resources :workouts, only: [:destroy, :create, :update, :view, :edit] do
    delete '/edit/removeExercise', to: "workouts#remove_exercise", as: "remove_exercise"
    patch 'edit/addExercise', to: "workouts#add_exercise", as: "add_exercise"
  end

  resources :exercises do
    resources :exercise_sets, only: [:destroy, :create, :edit, :update]
  end

  namespace :api do
    resources :routines, only: [:index, :create, :update, :destroy]
    resources :profiles, only: [:index, :show]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users, :controllers => { registrations: 'users/registrations' }
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!, only: [:logbook]

  def index
  end

  def about
  end

  def logbook
    @user = params[:id] ? User.find(params[:id]) : current_user
    @workouts = @user.workouts

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="md:container px-4">
  <h1 class="text-6xl font-bold text-slate-100 text-center">About carnage</h1>
  <h3 class="text-3xl font-bold text-slate-600 text-center mt-3 mb-5">Discipline is the path to freedom.</h3>
  <div class="grid grid-flow-col gap-4 w-2/3 mx-auto">
    <%= render(AboutPageFieldComponent.new(title: "What made you develop carnage?", contents: "Back when I started lifting (early 2021), I tried to look for a decent workot tracker. There are a few with decent features out there, they all suffer from the same problems: They either rely on old scientific literature or are all paid, which might not be very appealing to a lot of people. Carnage is my attempt at fixing that.")) %>

    <%= render(AboutPageFieldComponent.new(title: "Who are you?", contents: "I am a Portuguese college student with a passion for bodybuilding (one could say I cannot live without the gym!) and, as such, I decided to make my own workout tracker based off of my own ideas + some borrowed from others I've used in the past.")) %>

    <%= render(AboutPageFieldComponent.new(title: "What features does carnage have?", contents: "Pretty much everything other workout trackers have, with the exception of not having to pay for anything! However, contrary to most workout trackers, carnage is updated with the latest science (quality ALWAYS over quantity) and will take you to places no other workout tracker will ever do!")) %>
  </div>

app/views/welcome/dashboard.html.erb
<div class="md:container">
  <div class="text-slate-100 inline-flex items-center">
    <img class="object-scale-down h-20 w-20 rounded-full mr-3" src="https://i.pinimg.com/564x/b1/be/8f/b1be8fe6cd9e67ae26a480a1040c3733.jpg"></img>
    <p class="text-4xl text-slate-100 font-extrabold text-center"><%= current_user.username %></p>
  </div>
  <br>

  <div class="grid gap-3 mt-3 grid-flow-row">
    <p class="text-4xl font-extrabold text-slate-100">Overall Statistics</p> 
    <div class="grid grid-cols-3 grid-flow-col gap-2 my-5 mx-auto px-2">
      <%= render(StatisticsViewComponent.new(topText: "So far, you've got", bg: "bg-white", fg: "text-gray-700", midText:"#{current_user.workouts.count} workouts", bottomText: "Keep up the good work.")) %>
      <%= render(StatisticsViewComponent.new(bg:"bg-red-300", fg:"text-slate-100", topText: "Weekly volume", midText:"0", bottomText: "Some day you'll be able to lift a black hole!")) %>
      <%= render(StatisticsViewComponent.new(topText: "Weekly hard sets", bg: "bg-white", fg:"text-gray-700", midText: "0", bottomText: "\"5 MORE REPS - Tom Platz\"")) %>
    </div>

    <p class="text-4xl font-extrabold text-slate-100">Logbook</p>
    <div class="mx-2 text-gray-700 bg-white p-3 rounded-xl">
      <div class="bg-gray-100 overflow-auto max-h-44">
        <% if @workouts.count > 0 %>
          <% @workouts.each do |workout| %>
            <%= link_to workout.title, workout_path(workout.id), class: "text-2xl" %>
            <p class="inline-flex"> (<%= workout.created_at.strftime("%d/%m/%Y") %>)</p>
            <br>
          <% end %>
        <% else %>
          <p class="font-bold text-2xl">No workouts here!</p>
          <p class="ml-2">Added workouts will appear here.</p>
        <% end %>
      </div>
      <div class="inline-flex align-bottom gap-3 mt-3">
      <!--<button class="bg-red-300 text-slate-100 text-center p-1 rounded-xl">See more</button> -->
        <%= link_to "New workout", new_workout_path, class: "bg-red-300 text-slate-100 text-center p-1 rounded-xl" %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
  <div class="md:container mx-auto p-16">
      <div class="mx-auto text-center flex items-center justify-center">
      <img src="/assets/icon.png" class="w-[30px] sm:w-[90px]"></img>
      <p class="text-white ml-4 font-bold font-montserrat uppercase text-3xl sm:text-8xl">Carnage</p>
    </div>
    <br>
    <div class="mx-auto justify-center flex gap-5 sm:gap-10 font-montserrat font-semibold">
      <% if user_signed_in? %>
        <%= link_to "Logbook", logbook_path(id: current_user.id), class: "rounded-3xl hover:bg-carnage-red-pressed transition ease-in-out py-2 px-8 text-center text-white bg-carnage-red text-lg" %>
        <%= link_to "Statistics", logbook_path(id: current_user.id), class: "rounded-3xl py-2 w-44 text-center hover:bg-carnage-secondary-pressed transition ease-in-out text-white bg-carnage-secondary text-lg" %>
      <% else %>
        <div class="bg-carnage-secondary w-[400px]">
          <p class="text-white py-2 text-center rounded-3xl font-montserrat font-semibold outline-dashed outline-carnage-red">New here? Feel free to check out #about</p>
        </div>
      <% end %>
    </div>
  </div>

app/views/welcome/logbook.html.erb
<div class="mx-auto w-auto p-16">
<div class="mx-auto text-center flex items-center justify-center">
  <img src="/assets/icon.png" class="w-[30px] sm:w-[80px]"></img>
  <p class="text-white ml-4 font-bold font-montserrat uppercase text-3xl sm:text-7xl">Logbook</p>
</div>
<br>

<div class="md:container">
<div class="mx-2 text-white bg-carnage-secondary p-6 font-montserrat mt-2 rounded-3xl">
    <div class="overflow-auto max-h-44">
      <%= turbo_frame_tag "workouts" do %>
        <% if current_user.workouts.count > 0 %>
          <%= render partial: "workouts/workout", collection: @workouts %>
        <% else %>
          <p class="font-semibold text-2xl">No workouts found!</p>
          <p class="ml-2">Added workouts will appear here.</p>
        <% end %>
      <% end %>
    </div>
    <% if @user == current_user %>
        <div class="inline-flex align-bottom gap-3 mt-3 border-t-4 border-carnage-red w-full">
        <!--<button class="bg-red-300 text-slate-100 text-center p-1 rounded-xl">See more</button> -->
        </div>
    <% end %>
  </div>
</div>
</div>