config/routes.rb
Rails.application.routes.draw do
  resources :routines
  get 'welcome/index'
  get '/about', to: "welcome#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/logbook', to: "welcome#logbook", as: "logbook"

  resources :workouts, only: [:destroy, :create, :update, :view, :edit] do
    delete '/edit/removeExercise', to: "workouts#remove_exercise", as: "remove_exercise"
    patch 'edit/addExercise', to: "workouts#add_exercise", as: "add_exercise"
  end

  resources :exercises do
    resources :exercise_sets, only: [:destroy, :create, :edit, :update]
  end

  namespace :api do
    resources :routines, only: [:index, :create, :update, :destroy]
    resources :profiles, only: [:index, :show]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users, :controllers => { registrations: 'users/registrations' }
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  TYPES = [
    WEIGHT_REPS = "Weight and reps",
    REPS = "Reps only",
    TIMED = "timed"
  ] 
 

  def to_s = name

  has_many :exercise_sets, dependent: :destroy
  has_and_belongs_to_many :workouts
  has_and_belongs_to_many :muscle_groups
  belongs_to :user # Every single exercise was created by a user.

  validates :muscle_groups, :name, presence: true
  validates :exerciseType, inclusion: {in: TYPES}
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!, :find, only: [:edit, :update, :destroy]


  def find
    @exercise = Exercise.find(params[:id])
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = current_user.exercises.new(exercise_params)
    
    if @exercise.save
      redirect_to '/' 
    end
  end

  def exercise_params
    params.require(:exercise).permit(:name, :emphasis, :description, :exerciseType, muscle_group_ids: [])
  end

  def index
    @exercises = Exercise.all
  end

  def edit
  end

  def update 
    if @exercise.update(exercise_params)
      redirect_to exercises_path
    end
  end

  def destroy
    id = @exercise.id
    if @exercise.destroy
      respond_to do |format|
        format.html { redirect_back(fallback_location: '/') }
        format.turbo_stream {render turbo_stream: turbo_stream.remove("edit_exercise_#{id}")}
      end
    end
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_exercise.html.erb
<%= turbo_frame_tag dom_id(exercise, :edit) do %>
  <div class="bg-carnage-secondary text-white mb-2 p-4 rounded-2xl font-montserrat">
    <div class="flex justify-between">    <!--Image in the future-->
      <p class="font-semibold"><%= exercise.name %></p>

      <% if is_workout %>
        <div class="gap-5 flex">
            <%= button_to "X", workout_remove_exercise_path(exercise_id: exercise.id, workout_id: params[:workout_id] || params[:id]), method: :delete,
            class: "rounded-3xl font-semibold transition ease-in-out
                    text-center text-white hover:text-carnage-red-pressed" %>
        </div>
      <% end %>
    </div>

    <% exercise.muscle_groups.each do |mg| %>
      <p class="ml-2 text-sm"><%= mg.name %></p>
    <% end %>

    <% if exercise.emphasis.presence %>
      <p class="ml-2 text-sm"> (<%= exercise.emphasis %>)</p>
    <% end %>

    <div class="gap-2 mt-2 ml-2 text-center">
      <% if is_workout %>
          <% if exercise.exerciseType == Exercise::WEIGHT_REPS %>
            <%= turbo_frame_tag dom_id(exercise, "sets") do %>
              <% ExerciseSet.where(workout_id: params[:id], exercise_id: exercise.id).each do |x| %>
                <%= render x %>
              <% end %>
            <% end %>

          <%= button_to "+ Add set", exercise_exercise_sets_path(exercise_id: exercise.id, workout_id: params[:workout_id] || params[:id]),
            class: "mt-5 rounded-3xl font-semibold hover:bg-carnage-red-pressed transition ease-in-out py-2 px-8
                text-center text-white text-sm bg-carnage-red" %>
          <% end %>

      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<%= turbo_frame_tag dom_id(@exercise, :edit) do %>
  <div class="md:container">
    <p class="text-slate-100 text-4xl font-extrabold mb-2">Edit "<%= @exercise.name %>"</p>
    <div class="flex justify-center mx-auto p-3 text-slate-100 relative">
      <%= form_with model: @exercise do |form| %>
        <%= form.label :name, class: "font-bold mr-2" %>
        <%= form.text_field :name, class: "rounded-2xl mb-2 bg-zinc-900" %><br>

        <%= form.label :description, class: "font-bold mr-2" %>
        <%= form.text_field :description, class: "rounded-2xl mb-2 bg-zinc-900" %><br>

        <%= form.label :emphasis, class: "font-bold mr-2" %>
        <%= form.text_field :emphasis, class: "rounded-2xl mb-2 bg-zinc-900" %>

        <div class="flex justify-center mt-9 gap-5">
          <%= form.submit "Save changes", class: "outline hover:text-red-300 outline-400 outline-red-400 text-red-400 rounded-xl p-2 font-bold text-sm" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/exercises/index.html.erb
<div class="md:container">
  <div class="mx-auto max-h-[48rem] rounded-lg p-3 overflow-auto">
    <div class="flex justify-between items-center">
      <p class="text-4xl mb-2 text-white font-extrabold">Exercises</p>
      <%= link_to "+ New Exercise", new_exercise_path, class: "outline hover:text-teal-300 outline-400 outline-teal-400 text-teal-400 rounded-xl p-2 font-bold text-sm" %>
    </div>
    <div class="ml-2">
      <% @exercises.each do |ex| %>
        <%= render ex, is_workout: false do |b| %>
          <div class="flex justify-center gap-3">
            <%= link_to "Edit Exercise", edit_exercise_path(ex.id), class: "outline hover:text-teal-300 outline-400 outline-teal-400 text-teal-400 rounded-xl p-2 font-bold text-sm" %>
            <% if current_user.id == ex.user_id %>
              <%= button_to "Remove Exercise", exercise_path(ex.id), method: :delete, class: "outline hover:text-red-300 outline-400 outline-red-400 text-red-400 rounded-xl p-2 font-bold text-sm" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/exercises/new.html.erb
<script>
function displayModal() {
    const dialog = document.getElementById('dialog');
    dialog.showModal();
}
</script>

<div class="md:container mx-auto">
  <p class="text-center text-4xl text-slate-100 font-extrabold mb-9">New Exercise</p>
  <div class="flex justify-center relative">
    <%= form_with(model: @exercise) do |form| %>
      <%= render DialogComponent.new(title: "Add muscle groups", close_button_text: "Confirm") do |d| %>
        <%= form.collection_check_boxes :muscle_group_ids, MuscleGroup.all, :id, :name, {multiple: true}, {class: "text-blue-500"} do |f| %>
          <div class="flex justify-between text-slate-100">
            <%= f.text %>
            <%= f.check_box %>
          </div>
        <% end %>
      <% end %>
      <%= form.label :name, class: "font-bold text-slate-100 mr-2" %>
      <%= form.text_field :name, class: "bg-zinc-900 rounded-2xl text-slate-100 mb-3" %><br>
      
      <%= form.label :description, class: "font-bold text-slate-100 mr-2" %>
      <%= form.text_field :description, class: "bg-zinc-900 rounded-2xl text-slate-100 mb-3" %><br> 

      <%= form.label :emphasis, class: "font-bold text-slate-100 mr-2" %>
      <%= form.text_field :emphasis, class: "bg-zinc-900 rounded-2xl text-slate-100 mb-3" %><br>

      <%= form.label :exercise_type, class: "font-bold text-slate-100 mr-2" %>
      <%= form.collection_select :exerciseType, Exercise::TYPES, :to_s, :to_s, {}, {class: "text-slate-100 bg-zinc-900 rounded-xl"} %><br>
      
      <button type="button" onclick="document.getElementById('dialog').showModal();" class="bg-blue-500 text-xl font-bold text-slate-100 w-full mt-9 p-2 rounded-lg">Set Muscle Group</button>
      <%= form.submit class: "bg-red-500 text-slate-100 text-xl font-bold rounded-lg p-2 mt-2 w-full" %>
    
    <% end %>
  </div>
</div>